name: .NET Core

on: [push, pull_request]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x' # Specify the .NET version

    - name: Restore dependencies
      run: dotnet restore midterm-csharp-activity.sln

    - name: Build
      run: dotnet build midterm-csharp-activity.sln --configuration Release --no-restore

    - name: Run tests
      run: dotnet test my-console-app.Tests/my-console-app.Tests.csproj --configuration Release --no-build --verbosity normal